name: 'Deploy'
on:
  push:
    branches:
      - main

env:
  NODE_VERSION: '10.x'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_TOKEN_PERSONAL: ${{ secrets.GH_TOKEN_PERSONAL }}

jobs:
  build-and-deploy:
    name: Install, Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache node_modules
        id: cache-primes
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: npm install, build, and test
        env:
          BASE_PATH: ${{ secrets.BASE_PATH }}
        run: |
          npm install
          npm run generate
      - name: Push to pages
        uses: crazy-max/ghaction-github-pages@v1.2.4
        with:
          build_dir: dist
